version: "3.8"
services:
  ip-monitor:
    build: .
    container_name: ip_monitor
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - .:/app
